import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Hiretecky',
}

export default function TermsPage() {
  const lastUpdated = 'March 31, 2026'

  return (
    <div className="min-h-screen bg-white py-14">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: {lastUpdated}</p>

        <div className="space-y-8 text-sm leading-relaxed text-slate-700">
          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Hiretecky ("the Service"), you agree to be bound by these Terms of
              Service. If you are using the Service on behalf of a company, you represent that you have
              the authority to bind that company to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">2. Description of Service</h2>
            <p>
              Hiretecky provides a marketplace and deployment platform for AI automation agents.
              We configure, host, and maintain AI agents that perform defined business functions
              on behalf of our customers. The Service is provided on a subscription or project basis
              as described in your order or agreement.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">3. Subscriptions & Payment</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Subscriptions are billed monthly in advance</li>
              <li>All fees are non-refundable except as stated in our 14-day performance guarantee</li>
              <li>We may adjust pricing with 30 days written notice</li>
              <li>Failed payments result in service suspension after 7 days</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">4. 14-Day Performance Guarantee</h2>
            <p>
              If your AI agent does not meet the performance benchmarks agreed upon during onboarding
              within 14 days of deployment, we will reconfigure the agent at no additional cost or
              provide a full refund of the first month's subscription fee. This guarantee applies
              to the first deployment of each new agent type only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Send unsolicited bulk communications (spam)</li>
              <li>Violate applicable laws, including data protection regulations</li>
              <li>Misrepresent the AI nature of agent interactions where legally required to disclose</li>
              <li>Process data you do not have the right to process</li>
              <li>Attempt to reverse-engineer or extract our AI models or configurations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">6. Data Ownership</h2>
            <p>
              You retain full ownership of your business data. We process your data solely to
              provide the Service. We do not claim any rights to your data, customer data, or
              outputs generated by agents operating on your behalf. See our Privacy Policy for
              full data handling details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">7. Service Availability</h2>
            <p>
              We target 99.5% uptime for all active agent deployments. Planned maintenance will
              be communicated with at least 24 hours notice. Unplanned downtime exceeding 2 hours
              in a calendar month will be credited as a pro-rated service extension.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Hiretecky's liability for any claim arising
              from use of the Service is limited to the amount paid in the 3 months preceding the
              claim. We are not liable for indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">9. Termination</h2>
            <p>
              Either party may terminate with 30 days written notice. We may terminate immediately
              for material breach of these terms. Upon termination, your agent deployments will be
              decommissioned and your data will be returned or deleted per your instructions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">10. Governing Law</h2>
            <p>
              These terms are governed by the laws of the State of Delaware, United States, without
              regard to conflict of law provisions. Disputes will be resolved through binding
              arbitration in accordance with AAA Commercial Arbitration Rules.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-900 mb-3">11. Contact</h2>
            <p>
              Legal inquiries:{' '}
              <a href="mailto:legal@hiretecky.com" className="text-indigo-600 hover:underline">
                legal@hiretecky.com
              </a>
              {' '}· Hiretecky Inc. · hiretecky.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
