import { Agent } from './types'

export const agents: Agent[] = [
  {
    id: '1',
    slug: 'sales-lead-gen-agent',
    name: 'LeadForge AI',
    tagline: 'Prospect, qualify, and book meetings — around the clock',
    description:
      'LeadForge AI autonomously identifies high-intent leads, personalizes outreach at scale, follows up intelligently, and books discovery calls directly onto your calendar. Replace your SDR team with a tireless agent that never misses a follow-up.',
    category: 'Sales & Lead Gen',
    capabilities: [
      'Automated prospect research & scoring',
      'Personalized multi-channel outreach (email, LinkedIn)',
      'Follow-up sequences with smart timing',
      'CRM sync (HubSpot, Salesforce, Pipedrive)',
      'Meeting scheduling & calendar integration',
      'Real-time lead qualification',
    ],
    useCases: [
      'Outbound SDR replacement',
      'Pipeline generation for B2B SaaS',
      'Account-based marketing campaigns',
      'Event follow-up automation',
    ],
    integrations: ['HubSpot', 'Salesforce', 'LinkedIn', 'Gmail', 'Calendly', 'Apollo'],
    pricing: [
      {
        tier: 'Starter',
        price: 499,
        unit: 'per month',
        features: ['500 contacts/month', 'Email outreach', 'Basic CRM sync', 'Email support'],
      },
      {
        tier: 'Professional',
        price: 1499,
        unit: 'per month',
        features: [
          'Unlimited contacts',
          'Multi-channel outreach',
          'Full CRM integration',
          'Meeting booking',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 3999,
        unit: 'per month',
        features: [
          'Custom workflows',
          'Dedicated account manager',
          'Custom integrations',
          'SLA guarantee',
          'White-labeling',
        ],
      },
    ],
    rating: 4.8,
    reviewCount: 142,
    companiesUsing: 380,
    badge: 'Popular',
    icon: '🎯',
    color: 'indigo',
  },
  {
    id: '2',
    slug: 'customer-support-agent',
    name: 'SupportIQ AI',
    tagline: 'Resolve 80% of tickets instantly, delight every customer',
    description:
      'SupportIQ AI handles tier-1 and tier-2 customer support with human-level empathy. It learns from your knowledge base, escalates complex issues intelligently, and maintains consistent brand voice across every interaction.',
    category: 'Customer Support',
    capabilities: [
      'Instant ticket resolution (chat, email, phone)',
      'Knowledge base learning & continuous improvement',
      'Smart escalation to human agents',
      'Multi-language support (50+ languages)',
      'CSAT & sentiment tracking',
      'Proactive customer health monitoring',
    ],
    useCases: [
      'E-commerce order & returns support',
      'SaaS product onboarding & troubleshooting',
      'Banking & fintech customer service',
      '24/7 support coverage without overnight staff',
    ],
    integrations: ['Zendesk', 'Intercom', 'Freshdesk', 'Shopify', 'Stripe', 'Slack'],
    pricing: [
      {
        tier: 'Starter',
        price: 299,
        unit: 'per month',
        features: ['1,000 tickets/month', 'Chat & email', 'Knowledge base sync', 'Basic analytics'],
      },
      {
        tier: 'Professional',
        price: 999,
        unit: 'per month',
        features: [
          'Unlimited tickets',
          'All channels',
          'Custom workflows',
          'Advanced analytics',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 2999,
        unit: 'per month',
        features: [
          'Custom AI training',
          'Dedicated infrastructure',
          'SLA guarantee',
          'Custom integrations',
          'Compliance reporting',
        ],
      },
    ],
    rating: 4.9,
    reviewCount: 218,
    companiesUsing: 540,
    badge: 'Featured',
    icon: '💬',
    color: 'blue',
  },
  {
    id: '3',
    slug: 'hr-recruiting-agent',
    name: 'TalentMatch AI',
    tagline: 'Screen, schedule, and shortlist — hire faster than ever',
    description:
      'TalentMatch AI automates the full top-of-funnel recruiting process: posting jobs, screening resumes, conducting first-round assessments, scheduling interviews, and delivering ranked shortlists to your hiring managers.',
    category: 'HR & Recruiting',
    capabilities: [
      'Multi-platform job posting & management',
      'Resume screening & AI scoring',
      'Automated candidate outreach',
      'First-round async video/text interviews',
      'Interview scheduling & coordination',
      'Diversity & bias monitoring',
    ],
    useCases: [
      'High-volume hourly hiring',
      'Engineering & technical role screening',
      'Executive search coordination',
      'Campus & seasonal recruitment',
    ],
    integrations: ['LinkedIn', 'Indeed', 'Greenhouse', 'Lever', 'Workday', 'Google Calendar'],
    pricing: [
      {
        tier: 'Starter',
        price: 399,
        unit: 'per month',
        features: ['5 open roles', 'Resume screening', 'Email outreach', 'Basic reporting'],
      },
      {
        tier: 'Professional',
        price: 1199,
        unit: 'per month',
        features: [
          'Unlimited roles',
          'Video interviews',
          'ATS integrations',
          'Advanced analytics',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 3499,
        unit: 'per month',
        features: [
          'Custom assessment design',
          'HRIS integration',
          'Compliance suite',
          'Dedicated CSM',
          'Custom SLA',
        ],
      },
    ],
    rating: 4.7,
    reviewCount: 96,
    companiesUsing: 210,
    badge: 'New',
    icon: '👥',
    color: 'violet',
  },
  {
    id: '4',
    slug: 'marketing-content-agent',
    name: 'ContentFlow AI',
    tagline: 'Brief to published — content at the speed of your ideas',
    description:
      'ContentFlow AI turns your marketing strategy into a full content engine. Feed it a brief, and it researches, writes, optimizes for SEO, schedules, and distributes across every channel — consistently on brand.',
    category: 'Marketing & Content',
    capabilities: [
      'SEO-optimized blog & article writing',
      'Social media content calendar management',
      'Email newsletter drafting & scheduling',
      'Ad copy generation & A/B testing',
      'Brand voice learning & enforcement',
      'Performance analytics & iteration',
    ],
    useCases: [
      'Content marketing for B2B SaaS',
      'E-commerce product descriptions at scale',
      'Newsletter & email marketing automation',
      'Social media presence management',
    ],
    integrations: ['WordPress', 'HubSpot', 'Mailchimp', 'Buffer', 'Ahrefs', 'Canva'],
    pricing: [
      {
        tier: 'Starter',
        price: 349,
        unit: 'per month',
        features: ['10 articles/month', 'Social scheduling', 'Basic SEO', 'Email support'],
      },
      {
        tier: 'Professional',
        price: 999,
        unit: 'per month',
        features: [
          'Unlimited content',
          'Multi-channel distribution',
          'Advanced SEO',
          'A/B testing',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 2499,
        unit: 'per month',
        features: [
          'Custom brand training',
          'Dedicated strategist',
          'White-label reports',
          'Custom integrations',
          'SLA',
        ],
      },
    ],
    rating: 4.6,
    reviewCount: 87,
    companiesUsing: 295,
    icon: '✍️',
    color: 'pink',
  },
  {
    id: '5',
    slug: 'finance-accounting-agent',
    name: 'LedgerBot AI',
    tagline: 'Bookkeeping, reconciliation, and reporting on autopilot',
    description:
      'LedgerBot AI handles your full accounting workflow: categorizing transactions, reconciling accounts, generating financial reports, flagging anomalies, and preparing data for your CFO or CPA — with near-zero errors.',
    category: 'Finance & Accounting',
    capabilities: [
      'Automated transaction categorization',
      'Bank & credit card reconciliation',
      'Monthly P&L, balance sheet generation',
      'Accounts payable & receivable tracking',
      'Expense anomaly detection & alerts',
      'Tax preparation data packaging',
    ],
    useCases: [
      'SMB bookkeeping replacement',
      'Startup financial reporting',
      'E-commerce revenue reconciliation',
      'Multi-entity accounting',
    ],
    integrations: ['QuickBooks', 'Xero', 'Stripe', 'Plaid', 'Bill.com', 'NetSuite'],
    pricing: [
      {
        tier: 'Starter',
        price: 249,
        unit: 'per month',
        features: ['1 entity', 'Transaction categorization', 'Monthly reports', 'Email support'],
      },
      {
        tier: 'Professional',
        price: 799,
        unit: 'per month',
        features: [
          '3 entities',
          'Full reconciliation',
          'Custom reports',
          'Anomaly alerts',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 2199,
        unit: 'per month',
        features: [
          'Unlimited entities',
          'ERP integration',
          'Audit trail',
          'Dedicated accountant review',
          'Custom SLA',
        ],
      },
    ],
    rating: 4.8,
    reviewCount: 63,
    companiesUsing: 178,
    icon: '📊',
    color: 'emerald',
  },
  {
    id: '6',
    slug: 'software-dev-agent',
    name: 'DevPilot AI',
    tagline: 'Code review, bug fixes, and feature builds — autonomously',
    description:
      'DevPilot AI acts as a senior software engineer on your team — reviewing pull requests, catching bugs, writing tests, implementing features from tickets, and maintaining documentation. Integrated directly into your dev workflow.',
    category: 'Software Development',
    capabilities: [
      'Automated code review & PR comments',
      'Bug detection & fix suggestions',
      'Unit & integration test generation',
      'Feature implementation from Jira/Linear tickets',
      'Documentation generation & maintenance',
      'Security vulnerability scanning',
    ],
    useCases: [
      'Accelerate small dev teams',
      'Continuous code quality enforcement',
      'Legacy code refactoring & modernization',
      'Open source project maintenance',
    ],
    integrations: ['GitHub', 'GitLab', 'Jira', 'Linear', 'Slack', 'VS Code'],
    pricing: [
      {
        tier: 'Starter',
        price: 499,
        unit: 'per month',
        features: ['1 repo', 'Code review', 'Bug detection', 'Basic test gen'],
      },
      {
        tier: 'Professional',
        price: 1499,
        unit: 'per month',
        features: [
          '10 repos',
          'Feature implementation',
          'Full test coverage',
          'Security scanning',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 3999,
        unit: 'per month',
        features: [
          'Unlimited repos',
          'Custom AI training',
          'On-prem option',
          'Dedicated engineer',
          'SLA',
        ],
      },
    ],
    rating: 4.7,
    reviewCount: 104,
    companiesUsing: 260,
    badge: 'Popular',
    icon: '⚙️',
    color: 'slate',
  },
  {
    id: '7',
    slug: 'data-analytics-agent',
    name: 'InsightPulse AI',
    tagline: 'Ask your data anything. Get answers in seconds.',
    description:
      'InsightPulse AI connects to all your data sources and delivers actionable insights on demand. Ask questions in plain English, get dashboards, catch anomalies early, and automate your weekly reporting — no SQL required.',
    category: 'Data & Analytics',
    capabilities: [
      'Natural language data querying',
      'Automated dashboard generation',
      'Anomaly detection & alerting',
      'Scheduled report delivery',
      'Cross-source data correlation',
      'Predictive trend analysis',
    ],
    useCases: [
      'Executive KPI reporting automation',
      'Marketing campaign performance analysis',
      'Product usage & retention analytics',
      'Supply chain & inventory insights',
    ],
    integrations: ['Snowflake', 'BigQuery', 'Looker', 'Tableau', 'Amplitude', 'Google Analytics'],
    pricing: [
      {
        tier: 'Starter',
        price: 399,
        unit: 'per month',
        features: ['3 data sources', 'Basic dashboards', 'Weekly reports', 'Email support'],
      },
      {
        tier: 'Professional',
        price: 1199,
        unit: 'per month',
        features: [
          '20 data sources',
          'Custom dashboards',
          'Anomaly alerts',
          'Predictive analytics',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 2999,
        unit: 'per month',
        features: [
          'Unlimited sources',
          'Custom ML models',
          'Dedicated data engineer',
          'On-prem option',
          'SLA',
        ],
      },
    ],
    rating: 4.6,
    reviewCount: 71,
    companiesUsing: 190,
    icon: '📈',
    color: 'cyan',
  },
  {
    id: '8',
    slug: 'legal-compliance-agent',
    name: 'LexGuard AI',
    tagline: 'Contract review and compliance monitoring at legal-team scale',
    description:
      'LexGuard AI reviews contracts, flags risky clauses, monitors regulatory changes, and ensures your business stays compliant — without the $400/hr attorney bill. Built for in-house legal teams and growing companies.',
    category: 'Legal & Compliance',
    capabilities: [
      'Contract review & risk flagging',
      'NDA and vendor agreement analysis',
      'Regulatory change monitoring',
      'Policy document drafting',
      'IP & trademark watching',
      'Compliance checklist automation',
    ],
    useCases: [
      'SaaS vendor contract review',
      'GDPR / CCPA compliance monitoring',
      'Employment agreement standardization',
      'M&A due diligence support',
    ],
    integrations: ['DocuSign', 'Ironclad', 'Notion', 'Google Drive', 'Salesforce', 'Slack'],
    pricing: [
      {
        tier: 'Starter',
        price: 449,
        unit: 'per month',
        features: [
          '20 contracts/month',
          'Risk flagging',
          'Basic compliance',
          'Email support',
        ],
      },
      {
        tier: 'Professional',
        price: 1399,
        unit: 'per month',
        features: [
          'Unlimited contracts',
          'Regulatory monitoring',
          'Policy drafting',
          'Advanced analytics',
          'Priority support',
        ],
      },
      {
        tier: 'Enterprise',
        price: 3499,
        unit: 'per month',
        features: [
          'Custom legal training',
          'Dedicated legal ops',
          'eDiscovery support',
          'Audit logs',
          'Custom SLA',
        ],
      },
    ],
    rating: 4.7,
    reviewCount: 48,
    companiesUsing: 130,
    icon: '⚖️',
    color: 'amber',
  },
]

export function getAgentBySlug(slug: string): Agent | undefined {
  return agents.find((a) => a.slug === slug)
}

export function getAgentsByCategory(category: string): Agent[] {
  if (category === 'All') return agents
  return agents.filter((a) => a.category === category)
}

export const categories = [
  'All',
  'Sales & Lead Gen',
  'Customer Support',
  'HR & Recruiting',
  'Marketing & Content',
  'Finance & Accounting',
  'Software Development',
  'Data & Analytics',
  'Legal & Compliance',
  'Operations',
] as const
